// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnlSS_sbAYbTeWHhkDdH8jRAJmAHxBrIk',
    appId: '1:103900823975:web:4997d1b8e21dea4db7b682',
    messagingSenderId: '103900823975',
    projectId: 'instagram-clone-35eb4',
    authDomain: 'instagram-clone-35eb4.firebaseapp.com',
    storageBucket: 'instagram-clone-35eb4.appspot.com',
    measurementId: 'G-KG882K5ST7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoQ46_X-LHHLStc3MiRxAIU6gyj9LtVDk',
    appId: '1:103900823975:android:3a6f0399cb89ae00b7b682',
    messagingSenderId: '103900823975',
    projectId: 'instagram-clone-35eb4',
    storageBucket: 'instagram-clone-35eb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3XkGC64NSJI2J6rUpT1-gn9AUfBM4cc',
    appId: '1:103900823975:ios:7e3e0e91ba503a64b7b682',
    messagingSenderId: '103900823975',
    projectId: 'instagram-clone-35eb4',
    storageBucket: 'instagram-clone-35eb4.appspot.com',
    iosClientId: '103900823975-lo3ic4hh7qhkuipjqnotrgs6mt9vao62.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI3XkGC64NSJI2J6rUpT1-gn9AUfBM4cc',
    appId: '1:103900823975:ios:7e3e0e91ba503a64b7b682',
    messagingSenderId: '103900823975',
    projectId: 'instagram-clone-35eb4',
    storageBucket: 'instagram-clone-35eb4.appspot.com',
    iosClientId: '103900823975-lo3ic4hh7qhkuipjqnotrgs6mt9vao62.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
